import { createFirestoreModel, BaseDoc } from '../lib/firestoreModel';

export interface IInvoiceItem extends BaseDoc {
  frame?: string | any;
  opticalLens?: string | any;
  prescription?: string | any;
  fragrance?: string | any;
  eye?: 'left' | 'right' | 'both';
  userName?: string;
  spherical?: number;
  cylinder?: number;
  axis?: number;
  addition?: number;
  lensLabel?: string;
  quantity: number;
  price: number;
  costPrice?: number;
  mrp?: number;
  storePrice?: number;
  tier?: string;
  fragranceGrade?: string;
  lensBrand?: string;
  lensName?: string;
  lensCategory?: string;
  lensIndex?: string;
  lensCoating?: string;
  frameVariantLabel?: string;
  rightEyeNumber?: string;
  leftEyeNumber?: string;
  lensCompany?: string;
  lensType?: string;
  lensMaterial?: string;
  lensColor?: string;
  isCustomLens?: boolean;
  isSameNumber?: boolean;
  fulfillmentSource: 'stock' | 'ordered' | 'unfulfilled';
  requestedQty?: number | null;
  fulfilledQty?: number | null;
  sentToWholesaler?: boolean;
  wholesalerOrderDate?: Date | null;
  labStatus?: 'pending' | 'sent' | 'received' | 'fitted' | 'cancelled';
  labReceivedDate?: Date | null;
  labFittedDate?: Date | null;
  rightSpherical?: number | null;
  rightCylinder?: number | null;
  rightAxis?: number | null;
  rightAddition?: number | null;
  leftSpherical?: number | null;
  leftCylinder?: number | null;
  leftAxis?: number | null;
  leftAddition?: number | null;
  createdAt?: Date;
  updatedAt?: Date;
}

export const InvoiceItem = createFirestoreModel<IInvoiceItem>('invoiceitems');
